version: "3"
services:
  docker-soundboard:
    image: docker-soundboard
    build: .
    restart: always
    depends_on:
      - db    
    env_file: .env
    volumes:
      - ./files:/home/node/discord-soundboard-api/soundfiles
    networks:
      traefik:
      backend:
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: Host:${HOST_RULE}
      traefik.port: "3000"
      traefik.docker.network: traefik

  db:
    image: redis
    restart: always
    volumes:
      - ./data:/data
    networks:
      backend:



networks:
  traefik:
    external: true
  backend:
