version: "2"
services:
  docker-soundboard:
    image: docker-soundboard
    build: .
    restart: always
    depends_on:
      - db    
    environment:
      SOUNDBOARD_DISCORD_BOT_USER_TOKEN: ${SOUNDBOARD_DISCORD_BOT_USER_TOKEN}
      REDIS_HOST: 'db'
    volumes:
      - ./files:/home/node/discord-soundboard-api/soundfiles
    networks:
      traefik:
      backend:
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: Host:${HOST_RULE}
      traefik.port: "8080"
      traefik.docker.network: traefik

  db:
    image: redis
    restart: always
    volumes:
      - ./data:/data
    networks:
      backend:



networks:
  traefik:
    external: true
  backend:
